/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyaccountIndexRouteImport } from './routes/myaccount/index'
import { Route as ConfigurationIndexRouteImport } from './routes/configuration/index'
import { Route as PlayerFindAllRouteImport } from './routes/player/findAll'
import { Route as PlayerCreateRouteImport } from './routes/player/create'
import { Route as ClubFindAllRouteImport } from './routes/club/findAll'
import { Route as ClubCreateRouteImport } from './routes/club/create'
import { Route as ManagementUsersIndexRouteImport } from './routes/management/users/index'
import { Route as ManagementPlayersIndexRouteImport } from './routes/management/players/index'
import { Route as ManagementCompetitionsIndexRouteImport } from './routes/management/competitions/index'
import { Route as ManagementClubsIndexRouteImport } from './routes/management/clubs/index'
import { Route as ConfigurationSeasonsIndexRouteImport } from './routes/configuration/seasons/index'
import { Route as ConfigurationEventTypesIndexRouteImport } from './routes/configuration/event-types/index'
import { Route as ConfigurationCompetitionTypesIndexRouteImport } from './routes/configuration/competition-types/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as PlayerUpdateIdRouteImport } from './routes/player/update.$id'
import { Route as PlayerFindIdRouteImport } from './routes/player/find.$id'
import { Route as PlayerDeleteIdRouteImport } from './routes/player/delete.$id'
import { Route as ClubUpdateIdRouteImport } from './routes/club/update.$id'
import { Route as ClubFindOneIdRouteImport } from './routes/club/findOne.$id'
import { Route as ClubDeleteIdRouteImport } from './routes/club/delete.$id'
import { Route as AuthVerifyEmailIndexTokenRouteImport } from './routes/_auth/verify-email/index.$token'
import { Route as AuthResetPasswordIndexTokenRouteImport } from './routes/_auth/reset-password/index.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyaccountIndexRoute = MyaccountIndexRouteImport.update({
  id: '/myaccount/',
  path: '/myaccount/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationIndexRoute = ConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerFindAllRoute = PlayerFindAllRouteImport.update({
  id: '/player/findAll',
  path: '/player/findAll',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerCreateRoute = PlayerCreateRouteImport.update({
  id: '/player/create',
  path: '/player/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubFindAllRoute = ClubFindAllRouteImport.update({
  id: '/club/findAll',
  path: '/club/findAll',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubCreateRoute = ClubCreateRouteImport.update({
  id: '/club/create',
  path: '/club/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementUsersIndexRoute = ManagementUsersIndexRouteImport.update({
  id: '/management/users/',
  path: '/management/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPlayersIndexRoute = ManagementPlayersIndexRouteImport.update({
  id: '/management/players/',
  path: '/management/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementCompetitionsIndexRoute =
  ManagementCompetitionsIndexRouteImport.update({
    id: '/management/competitions/',
    path: '/management/competitions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementClubsIndexRoute = ManagementClubsIndexRouteImport.update({
  id: '/management/clubs/',
  path: '/management/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationSeasonsIndexRoute =
  ConfigurationSeasonsIndexRouteImport.update({
    id: '/configuration/seasons/',
    path: '/configuration/seasons/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfigurationEventTypesIndexRoute =
  ConfigurationEventTypesIndexRouteImport.update({
    id: '/configuration/event-types/',
    path: '/configuration/event-types/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfigurationCompetitionTypesIndexRoute =
  ConfigurationCompetitionTypesIndexRouteImport.update({
    id: '/configuration/competition-types/',
    path: '/configuration/competition-types/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/_auth/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUpdateIdRoute = PlayerUpdateIdRouteImport.update({
  id: '/player/update/$id',
  path: '/player/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerFindIdRoute = PlayerFindIdRouteImport.update({
  id: '/player/find/$id',
  path: '/player/find/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerDeleteIdRoute = PlayerDeleteIdRouteImport.update({
  id: '/player/delete/$id',
  path: '/player/delete/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubUpdateIdRoute = ClubUpdateIdRouteImport.update({
  id: '/club/update/$id',
  path: '/club/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubFindOneIdRoute = ClubFindOneIdRouteImport.update({
  id: '/club/findOne/$id',
  path: '/club/findOne/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubDeleteIdRoute = ClubDeleteIdRouteImport.update({
  id: '/club/delete/$id',
  path: '/club/delete/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailIndexTokenRoute =
  AuthVerifyEmailIndexTokenRouteImport.update({
    id: '/_auth/verify-email/index/$token',
    path: '/verify-email/index/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordIndexTokenRoute =
  AuthResetPasswordIndexTokenRouteImport.update({
    id: '/_auth/reset-password/index/$token',
    path: '/reset-password/index/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club/create': typeof ClubCreateRoute
  '/club/findAll': typeof ClubFindAllRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/findAll': typeof PlayerFindAllRoute
  '/configuration': typeof ConfigurationIndexRoute
  '/myaccount': typeof MyaccountIndexRoute
  '/club/delete/$id': typeof ClubDeleteIdRoute
  '/club/findOne/$id': typeof ClubFindOneIdRoute
  '/club/update/$id': typeof ClubUpdateIdRoute
  '/player/delete/$id': typeof PlayerDeleteIdRoute
  '/player/find/$id': typeof PlayerFindIdRoute
  '/player/update/$id': typeof PlayerUpdateIdRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/configuration/competition-types': typeof ConfigurationCompetitionTypesIndexRoute
  '/configuration/event-types': typeof ConfigurationEventTypesIndexRoute
  '/configuration/seasons': typeof ConfigurationSeasonsIndexRoute
  '/management/clubs': typeof ManagementClubsIndexRoute
  '/management/competitions': typeof ManagementCompetitionsIndexRoute
  '/management/players': typeof ManagementPlayersIndexRoute
  '/management/users': typeof ManagementUsersIndexRoute
  '/reset-password/index/$token': typeof AuthResetPasswordIndexTokenRoute
  '/verify-email/index/$token': typeof AuthVerifyEmailIndexTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club/create': typeof ClubCreateRoute
  '/club/findAll': typeof ClubFindAllRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/findAll': typeof PlayerFindAllRoute
  '/configuration': typeof ConfigurationIndexRoute
  '/myaccount': typeof MyaccountIndexRoute
  '/club/delete/$id': typeof ClubDeleteIdRoute
  '/club/findOne/$id': typeof ClubFindOneIdRoute
  '/club/update/$id': typeof ClubUpdateIdRoute
  '/player/delete/$id': typeof PlayerDeleteIdRoute
  '/player/find/$id': typeof PlayerFindIdRoute
  '/player/update/$id': typeof PlayerUpdateIdRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/configuration/competition-types': typeof ConfigurationCompetitionTypesIndexRoute
  '/configuration/event-types': typeof ConfigurationEventTypesIndexRoute
  '/configuration/seasons': typeof ConfigurationSeasonsIndexRoute
  '/management/clubs': typeof ManagementClubsIndexRoute
  '/management/competitions': typeof ManagementCompetitionsIndexRoute
  '/management/players': typeof ManagementPlayersIndexRoute
  '/management/users': typeof ManagementUsersIndexRoute
  '/reset-password/index/$token': typeof AuthResetPasswordIndexTokenRoute
  '/verify-email/index/$token': typeof AuthVerifyEmailIndexTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club/create': typeof ClubCreateRoute
  '/club/findAll': typeof ClubFindAllRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/findAll': typeof PlayerFindAllRoute
  '/configuration/': typeof ConfigurationIndexRoute
  '/myaccount/': typeof MyaccountIndexRoute
  '/club/delete/$id': typeof ClubDeleteIdRoute
  '/club/findOne/$id': typeof ClubFindOneIdRoute
  '/club/update/$id': typeof ClubUpdateIdRoute
  '/player/delete/$id': typeof PlayerDeleteIdRoute
  '/player/find/$id': typeof PlayerFindIdRoute
  '/player/update/$id': typeof PlayerUpdateIdRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/configuration/competition-types/': typeof ConfigurationCompetitionTypesIndexRoute
  '/configuration/event-types/': typeof ConfigurationEventTypesIndexRoute
  '/configuration/seasons/': typeof ConfigurationSeasonsIndexRoute
  '/management/clubs/': typeof ManagementClubsIndexRoute
  '/management/competitions/': typeof ManagementCompetitionsIndexRoute
  '/management/players/': typeof ManagementPlayersIndexRoute
  '/management/users/': typeof ManagementUsersIndexRoute
  '/_auth/reset-password/index/$token': typeof AuthResetPasswordIndexTokenRoute
  '/_auth/verify-email/index/$token': typeof AuthVerifyEmailIndexTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club/create'
    | '/club/findAll'
    | '/player/create'
    | '/player/findAll'
    | '/configuration'
    | '/myaccount'
    | '/club/delete/$id'
    | '/club/findOne/$id'
    | '/club/update/$id'
    | '/player/delete/$id'
    | '/player/find/$id'
    | '/player/update/$id'
    | '/forgot-password'
    | '/login'
    | '/configuration/competition-types'
    | '/configuration/event-types'
    | '/configuration/seasons'
    | '/management/clubs'
    | '/management/competitions'
    | '/management/players'
    | '/management/users'
    | '/reset-password/index/$token'
    | '/verify-email/index/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club/create'
    | '/club/findAll'
    | '/player/create'
    | '/player/findAll'
    | '/configuration'
    | '/myaccount'
    | '/club/delete/$id'
    | '/club/findOne/$id'
    | '/club/update/$id'
    | '/player/delete/$id'
    | '/player/find/$id'
    | '/player/update/$id'
    | '/forgot-password'
    | '/login'
    | '/configuration/competition-types'
    | '/configuration/event-types'
    | '/configuration/seasons'
    | '/management/clubs'
    | '/management/competitions'
    | '/management/players'
    | '/management/users'
    | '/reset-password/index/$token'
    | '/verify-email/index/$token'
  id:
    | '__root__'
    | '/'
    | '/club/create'
    | '/club/findAll'
    | '/player/create'
    | '/player/findAll'
    | '/configuration/'
    | '/myaccount/'
    | '/club/delete/$id'
    | '/club/findOne/$id'
    | '/club/update/$id'
    | '/player/delete/$id'
    | '/player/find/$id'
    | '/player/update/$id'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/configuration/competition-types/'
    | '/configuration/event-types/'
    | '/configuration/seasons/'
    | '/management/clubs/'
    | '/management/competitions/'
    | '/management/players/'
    | '/management/users/'
    | '/_auth/reset-password/index/$token'
    | '/_auth/verify-email/index/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubCreateRoute: typeof ClubCreateRoute
  ClubFindAllRoute: typeof ClubFindAllRoute
  PlayerCreateRoute: typeof PlayerCreateRoute
  PlayerFindAllRoute: typeof PlayerFindAllRoute
  ConfigurationIndexRoute: typeof ConfigurationIndexRoute
  MyaccountIndexRoute: typeof MyaccountIndexRoute
  ClubDeleteIdRoute: typeof ClubDeleteIdRoute
  ClubFindOneIdRoute: typeof ClubFindOneIdRoute
  ClubUpdateIdRoute: typeof ClubUpdateIdRoute
  PlayerDeleteIdRoute: typeof PlayerDeleteIdRoute
  PlayerFindIdRoute: typeof PlayerFindIdRoute
  PlayerUpdateIdRoute: typeof PlayerUpdateIdRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  ConfigurationCompetitionTypesIndexRoute: typeof ConfigurationCompetitionTypesIndexRoute
  ConfigurationEventTypesIndexRoute: typeof ConfigurationEventTypesIndexRoute
  ConfigurationSeasonsIndexRoute: typeof ConfigurationSeasonsIndexRoute
  ManagementClubsIndexRoute: typeof ManagementClubsIndexRoute
  ManagementCompetitionsIndexRoute: typeof ManagementCompetitionsIndexRoute
  ManagementPlayersIndexRoute: typeof ManagementPlayersIndexRoute
  ManagementUsersIndexRoute: typeof ManagementUsersIndexRoute
  AuthResetPasswordIndexTokenRoute: typeof AuthResetPasswordIndexTokenRoute
  AuthVerifyEmailIndexTokenRoute: typeof AuthVerifyEmailIndexTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myaccount/': {
      id: '/myaccount/'
      path: '/myaccount'
      fullPath: '/myaccount'
      preLoaderRoute: typeof MyaccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/': {
      id: '/configuration/'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/findAll': {
      id: '/player/findAll'
      path: '/player/findAll'
      fullPath: '/player/findAll'
      preLoaderRoute: typeof PlayerFindAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/create': {
      id: '/player/create'
      path: '/player/create'
      fullPath: '/player/create'
      preLoaderRoute: typeof PlayerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/findAll': {
      id: '/club/findAll'
      path: '/club/findAll'
      fullPath: '/club/findAll'
      preLoaderRoute: typeof ClubFindAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/create': {
      id: '/club/create'
      path: '/club/create'
      fullPath: '/club/create'
      preLoaderRoute: typeof ClubCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/users/': {
      id: '/management/users/'
      path: '/management/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof ManagementUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/players/': {
      id: '/management/players/'
      path: '/management/players'
      fullPath: '/management/players'
      preLoaderRoute: typeof ManagementPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/competitions/': {
      id: '/management/competitions/'
      path: '/management/competitions'
      fullPath: '/management/competitions'
      preLoaderRoute: typeof ManagementCompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/clubs/': {
      id: '/management/clubs/'
      path: '/management/clubs'
      fullPath: '/management/clubs'
      preLoaderRoute: typeof ManagementClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/seasons/': {
      id: '/configuration/seasons/'
      path: '/configuration/seasons'
      fullPath: '/configuration/seasons'
      preLoaderRoute: typeof ConfigurationSeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/event-types/': {
      id: '/configuration/event-types/'
      path: '/configuration/event-types'
      fullPath: '/configuration/event-types'
      preLoaderRoute: typeof ConfigurationEventTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/competition-types/': {
      id: '/configuration/competition-types/'
      path: '/configuration/competition-types'
      fullPath: '/configuration/competition-types'
      preLoaderRoute: typeof ConfigurationCompetitionTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/update/$id': {
      id: '/player/update/$id'
      path: '/player/update/$id'
      fullPath: '/player/update/$id'
      preLoaderRoute: typeof PlayerUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/find/$id': {
      id: '/player/find/$id'
      path: '/player/find/$id'
      fullPath: '/player/find/$id'
      preLoaderRoute: typeof PlayerFindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/delete/$id': {
      id: '/player/delete/$id'
      path: '/player/delete/$id'
      fullPath: '/player/delete/$id'
      preLoaderRoute: typeof PlayerDeleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/update/$id': {
      id: '/club/update/$id'
      path: '/club/update/$id'
      fullPath: '/club/update/$id'
      preLoaderRoute: typeof ClubUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/findOne/$id': {
      id: '/club/findOne/$id'
      path: '/club/findOne/$id'
      fullPath: '/club/findOne/$id'
      preLoaderRoute: typeof ClubFindOneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/delete/$id': {
      id: '/club/delete/$id'
      path: '/club/delete/$id'
      fullPath: '/club/delete/$id'
      preLoaderRoute: typeof ClubDeleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email/index/$token': {
      id: '/_auth/verify-email/index/$token'
      path: '/verify-email/index/$token'
      fullPath: '/verify-email/index/$token'
      preLoaderRoute: typeof AuthVerifyEmailIndexTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/index/$token': {
      id: '/_auth/reset-password/index/$token'
      path: '/reset-password/index/$token'
      fullPath: '/reset-password/index/$token'
      preLoaderRoute: typeof AuthResetPasswordIndexTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubCreateRoute: ClubCreateRoute,
  ClubFindAllRoute: ClubFindAllRoute,
  PlayerCreateRoute: PlayerCreateRoute,
  PlayerFindAllRoute: PlayerFindAllRoute,
  ConfigurationIndexRoute: ConfigurationIndexRoute,
  MyaccountIndexRoute: MyaccountIndexRoute,
  ClubDeleteIdRoute: ClubDeleteIdRoute,
  ClubFindOneIdRoute: ClubFindOneIdRoute,
  ClubUpdateIdRoute: ClubUpdateIdRoute,
  PlayerDeleteIdRoute: PlayerDeleteIdRoute,
  PlayerFindIdRoute: PlayerFindIdRoute,
  PlayerUpdateIdRoute: PlayerUpdateIdRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  ConfigurationCompetitionTypesIndexRoute:
    ConfigurationCompetitionTypesIndexRoute,
  ConfigurationEventTypesIndexRoute: ConfigurationEventTypesIndexRoute,
  ConfigurationSeasonsIndexRoute: ConfigurationSeasonsIndexRoute,
  ManagementClubsIndexRoute: ManagementClubsIndexRoute,
  ManagementCompetitionsIndexRoute: ManagementCompetitionsIndexRoute,
  ManagementPlayersIndexRoute: ManagementPlayersIndexRoute,
  ManagementUsersIndexRoute: ManagementUsersIndexRoute,
  AuthResetPasswordIndexTokenRoute: AuthResetPasswordIndexTokenRoute,
  AuthVerifyEmailIndexTokenRoute: AuthVerifyEmailIndexTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
